# Generated by Django 4.2.6 on 2023-12-06 08:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_group_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('show_group', django.db.models.manager.Manager()),
            ],
        ),
    ]
